### ISSUE TITLE
Building info gone from next intro course

### ISSUE THREAD

**Issue by richardbeare** [MonashDataFluency/data-fluency-website#3]
Hi,
The restructure of the site has lost a few bits and pieces of critical info - the room location (and list of instructors and helpers) is now missing from the introduction course planned for the 18th, and there's no way to navigate to the old page via the links.

**Comment by pansapiens** [comment]
Sorry Richard - didn't notice this until it's a bit late.

The correct URL is https://monashdatafluency.github.io/workshops/intro_to_r/20190218-intro-to-r/ - it looks as if the building info is there.

In the past links to the upcoming workshop page have been provided via the EventBrite event and pre-workshop email(s) to participants but not typically not linked on the front page at monashdatafluency.github.io until after the event.

If you are referring to this event page: https://www.monash.edu/data-fluency/events/introduction-to-r2 - yes, the building info is missing. I've only just become aware that these event pages even existed. The Monash hosted site is managed by Monash library staff - I've sent you some contact info via Slack.
